### PR TITLE
adds the ability to specify kafka class on startup

### PR DESCRIPTION
**Pull request by popsikle**
the options in the service was needed to pass extra_args to the kafka service.

### CODE REVIEW

**Comment by bbaugher** [comment]
I'm fine adding options to pass to the start script but the start/stop scripts in the cookbook were to handle bugs in certain confluent versions. Those scripts will only be deployed for that version, [here](https://github.com/popsikle/confluent/blob/0ab42867399d6fd70936988914fb443b94a7069d/recipes/_install.rb#L53-L54) and [here](https://github.com/popsikle/confluent/blob/0ab42867399d6fd70936988914fb443b94a7069d/recipes/_install.rb#L62-L63)

**Comment by popsikle** [comment]
kakfa-start is a not_if so it gets generated all the time, unless version is 1.0, im guessing that is a mistake then?

**Comment by bbaugher** [comment]
Yes thats a mistake

**Comment by popsikle** [comment]
ok, well thats good to know, because i was setting the class in the startup script to be what confluent 3.1.2 uses, which was the reason for this pull!

**Comment by bbaugher** [comment]
I fixed the issue here, https://github.com/bbaugher/confluent/issues/20

**Pull request closed without merging**
